### ISSUE TITLE
Update NLog to latest version, instead of BETA

### ISSUE THREAD

**Issue by snakefoot** [iiwaasnet/kino#15]
https://github.com/iiwaasnet/kino/blob/ef7f7106718538d48b6ddffb014a14e9b3b9ec46/src/Samples/Server/Server.csproj#L15

NLog 4.5.0 RTM has been released for NetCore: https://www.nuget.org/packages/NLog/

**Comment by iiwaasnet** [comment]
Do you want to issue a PR for that?
